php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=0 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=3000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=6000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=9000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=12000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=15000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=18000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=21000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=24000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=27000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=30000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=33000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=36000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=39000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=42000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=45000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=48000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=51000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=54000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=57000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=60000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=63000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=66000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=69000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=72000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=75000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=78000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=81000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=84000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=87000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=90000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=93000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=96000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=99000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=102000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=105000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=108000 >> storage/logs/import_id_zetcom.log 2>&1
php artisan gobelins:update:zetcom-product-id --all --limit=3000 --offset=111000 >> storage/logs/import_id_zetcom.log 2>&1
